### PR TITLE
Made mousehook optional for InputManager

### LINKED ISSUE #4: Option to not initialize mousehook in inputmanager.
I have a project where I don't care about mouse-hooking at all. I only listen to a select few keypresses and since InputManager has a nice subscription-system on a per-key-basis I use that. But debugging the program becomes a pain because the mouse-hook is installed no matter what and you can't disable it, the mouse is extremely sluggish as a result.
Are you still working on this project at all?

### PR DESCRIPTION
**Pull request by calledude**
Added an option to turn off the mouse-hook completely. 
The mouse-hook installs as default unless otherwise specified.

Fixes #4

### CODE REVIEW

**Comment by michel-pi** [comment]
i am going to update the NuGet package within the next hour. you can close your issue if you want to.

**Comment by calledude** [comment]
Github closes referenced issues automatically upon merge ;)

**Comment by calledude** [comment]
Did you forget to update the nuget package? :)

**Comment by michel-pi** [comment]
I am so sorry but i really had no time for it. I will do it now

**Comment by calledude** [comment]
No problem <3

**Comment by michel-pi** [comment]
i uploaded the package. it will take about 5 to 10 minutes to show up.
And i also want to add that i am probably going to re-code the whole library.
I will carry your changes over then.

**Comment by calledude** [comment]
Alright! I've only really had one gripe with this library, it doesn't recognize anything but capital letters, might be a thing to look into if you're going to rewrite it :)

**Comment by michel-pi** [comment]
The VirtualKeyCode enum just has those upper case letters. The hook does not check if the capslock or shift key is currently pressed. You need to add that yourself

**Pull request merged**
